name: Build and Deploy to AWS
on:
  push:
    branches:
      - 'dev/HOD-**'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The target deployment environment

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && 'Development' || inputs.environment }}
  cancel-in-progress: false

jobs:
  build-gov-cloud:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'Development' || inputs.environment }}
    outputs:
      api-invoke-url: ${{ steps.stack-outputs.outputs.invoke-url }}

    steps:
      ### Setup ###
      - uses: actions/checkout@v7
        name: Checkout code
      - uses: aws-actions/configure-aws-credentials@v6
        name: Configure AWS credentials
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_GOV }}
          aws-region: ${{ vars.AWS_REGION_GOV }}
      - name: Setup Node.JS
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
      - name: Add Environment Variables
        run: |-
          echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)" >> $GITHUB_ENV
          echo "NODE_VERSION=$(tr -cd '0-9' < .node-version)" >> $GITHUB_ENV
      ### Build Source ###
      ### Build Lambdas ###
      - name: Install Lambda Dependencies
        working-directory: ./lambda-functions
        run: npm ci
      - name: Compile Lambda Typescript
        working-directory: ./lambda-functions
        run: npm run build
      - name: Create package.json For Lambda Functions
        working-directory: ./lambda-functions
        run: node copy-package.js
      - name: Move Lambda Functions to CDK Directory
        run: |-
          mkdir -p ./cdk/code/lambda/functions
          mkdir -p ./cdk/code/lambda/common/nodejs
          cp -r ./lambda-functions/dist/src/functions/* ./cdk/code/lambda/functions
          cp -r ./lambda-functions/dist/src/common/* ./cdk/code/lambda/common/nodejs
      - name: Create Runtime Dependencies for Lambda Functions
        env:
          NODE_ENV: production
        run: |-
          mkdir -p ./cdk/code/lambda/functions/runtime-deps/nodejs
          cp ./lambda-functions/package.json ./cdk/code/lambda/functions/runtime-deps/nodejs
          cp ./lambda-functions/package-lock.json ./cdk/code/lambda/functions/runtime-deps/nodejs
          cd ./cdk/code/lambda/functions/runtime-deps/nodejs
          npm ci
          rm package.json package-lock.json
      ### Deploy Cloud ###
      - name: Install CDK Dependencies
        working-directory: ./cdk
        run: npm ci
      - name: Deploy CDK
        working-directory: ./cdk
        env:
          STACK_NAME: 'hod-oauth'
          AWS_PARTITION: 'gov-cloud'
          VPC_ID: ${{ vars.VPC_ID }}
          PRIVATE_SUBNET_IDS: ${{ vars.PRIVATE_SUBNETS }}
          AUTH_DOMAIN: ${{ vars.SERVER_HOST }}
          ENVIRONMENT_NAME: ${{ github.event_name == 'push' && 'Development' || inputs.environment }}
        run: |-
          npm run cdk -- bootstrap
          npm run cdk -- synth
          npm run cdk -- deploy --require-approval never
      - name: Create Stack Outputs
        id: stack-outputs
        run: |-
          echo "invoke-url=$(aws cloudformation describe-stacks --stack-name hod-oauth --query "Stacks[0].Outputs[?OutputKey=='OAuthApiUrl'].OutputValue" --output text)" >> $GITHUB_OUTPUT
  build-commercial:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'Development' || inputs.environment }}
    needs: [build-gov-cloud]
    steps:
      ### Setup ###
      - uses: actions/checkout@v7
        name: Checkout code
      - run: echo "${{ needs.build-gov-cloud.outputs.api-invoke-url }}"

